# Generated by Django 5.0.6 on 2025-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('land_area', models.FloatField()),
                ('assets_worth', models.FloatField()),
                ('previous_loans', models.FloatField()),
                ('paid_loans', models.FloatField()),
                ('ongoing_loans', models.FloatField()),
                ('assets_insurance_coverage', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('water_availability', models.CharField(max_length=255)),
                ('land_ownership', models.CharField(max_length=255)),
                ('soil_quality', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('credit_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
