# Generated by Django 5.0.6 on 2025-03-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmer',
            table='hackapp_farmer',
        ),
    ]
